stages:
  - build
  - test
  - package
  - trigger_deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build

package:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker build -t bas-world-fe:latest .

trigger_deploy:
  stage: trigger_deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  trigger:
    project: s3-cb/spring-26/fsd1-basworld/group-project-3/bas-world-group-3-infra
    branch: main