stages:
  - build
  - test
  - package
  - trigger_deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build

package:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - docker build 
      --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL
      --build-arg VITE_SUPABASE_URL=$VITE_SUPABASE_URL
      --build-arg VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
      --build-arg VITE_WS_URL
      -t bas-world-fe:latest .

trigger_deploy:
  stage: trigger_deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  trigger:
    project: s3-cb/spring-26/fsd1-basworld/group-project-3/bas-world-group-3-infra
    branch: main